### ISSUE TITLE
ClassCastException when walking over input types that have GraphQLTypeReferences

### ISSUE THREAD

**Issue by edudar-chwy** [graphql-java/graphql-java-extended-validation#99]
**Describe the bug**
```
java.lang.ClassCastException: class graphql.schema.GraphQLTypeReference cannot be cast to class graphql.schema.GraphQLUnmodifiedType (graphql.schema.GraphQLTypeReference and graphql.schema.GraphQLUnmodifiedType are in unnamed module of loader 'app')
  at graphql.schema.GraphQLTypeUtil.unwrapAll(GraphQLTypeUtil.java:194)
  at graphql.validation.util.DirectivesAndTypeWalker.walkInputType(DirectivesAndTypeWalker.java:23)
  at graphql.validation.util.DirectivesAndTypeWalker.isSuitable(DirectivesAndTypeWalker.java:19)
```

**To Reproduce** 
I have an enum type that is used as non-null input
```
enum SlotType {
    AVAILABLE, UNAVAILABLE
}

type Employee {
  schedule(type: SlotType!): [Slot!]!
}
```

`DirectivesAndTypeWalker` uses `GraphQLTypeUtil.unwrapAll(inputType)` since https://github.com/graphql-java/graphql-java-extended-validation/pull/34 but `unwrapAll` specifically says that it does not support `GraphQLTypeReference`:
```
Unwraps all layers of the type or just returns the type again if it's not a wrapped type NOTE: This method does not support GraphQLTypeReference as input and will lead to a ClassCastException
```

and `SlotType` turns out to be one:
```
type = {GraphQLNonNull@17904} "SlotType!"
 originalWrappedType = {GraphQLTypeReference@17955} "GraphQLTypeReference{name='SlotType'}"
  name = "SlotType"
 replacedWrappedType = null
```

**Comment by dondonz** [comment]
Hello, to help me understand the issue can you please provide a minimal test case as a pull request or reproduction of the bug in a repo? Thanks
